[project]
name = "arxiv-mcp"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "pytest",
    "httpx",
    "matplotlib",
    "pandas"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]