[project]
name = "scientific-mcp-server"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "pytest",
    "httpx",
    "matplotlib",
    "pandas"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

