[project]
name = "parquet-mcp"
version = "1.0.0"
description = "MCP server for Apache Parquet files"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Gnosis Research Center", email = "grc@illinoistech.edu" }
]

keywords = ["parquet", "columnar-data", "data-analysis", "scientific-computing", "mcp", "llm-integration", "apache-arrow"]

dependencies = [
    "fastmcp>=2.13.0.1",
    "pyarrow>=22.0.0",
    "pydantic>=2.12.3",
]

[project.urls]
Homepage = "https://iowarp.github.io/iowarp-mcps/"
Repository = "https://github.com/iowarp/iowarp-mcps"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "ruff>=0.12.5",
]

[project.scripts]
parquet-mcp = "parquet_mcp.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/parquet_mcp"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
asyncio_mode = "auto"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
