[project]
name = "mcp-server"
version = "0.1.0"
description = "A basic MCP server for scientific computing."
authors = [{ name = "Yudong Huang" }]
requires-python = ">=3.10"

dependencies = [
    "fastapi",
    "uvicorn",
    "pytest"
]

[tool.uv]
