title: Scientific MCPs
description: Scientific computing tools for AI agents and LLMs
url: https://iowarp.github.io
baseurl: /scientific-mcps
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collection configuration
collections:
  mcps:
    output: true
    permalink: /mcps/:name/

# Default values
defaults:
  - scope:
      path: ""
      type: "mcps"
    values:
      layout: "mcp"