name: Generate MCP Documentation

on:
  push:
    branches: [workflow/docusaurus-for-webpage, main]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Generate MCP documentation
      run: python3 readme_toml_merge.py