name: Auto-update MCP README files

on:
  pull_request:
    branches: [ dev ]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: |
          if [ -f pyproject.toml ]; then
            uv sync
          fi

      - name: Run README updater
        run: python3 readme_filler.py mcps

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if [[ -n $(git status --porcelain) ]]; then
            git add mcps/*/README.md
            git commit -m "Auto-update MCP README files"
            git push
          else
            echo "No README changes to commit"
          fi